config/routes.rb
Rails.application.routes.draw do
  resources :notifications
  resources :media_items
  resources :encoding_profiles
  post 'sns_endpoint' => 'sns#sns_endpoint'

end

app/models/encoding_profile.rb
class EncodingProfile < ActiveRecord::Base
end

app/models/media_item.rb
class MediaItem < ActiveRecord::Base
end

app/models/notification.rb
class Notification < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/encoding_profiles_controller.rb
class EncodingProfilesController < ApplicationController
  before_action :set_encoding_profile, only: [:show, :edit, :update, :destroy]

  # GET /encoding_profiles
  # GET /encoding_profiles.json
  def index
    @encoding_profiles = EncodingProfile.all
  end

  # GET /encoding_profiles/1
  # GET /encoding_profiles/1.json
  def show
  end

  # GET /encoding_profiles/new
  def new
    @encoding_profile = EncodingProfile.new
  end

  # GET /encoding_profiles/1/edit
  def edit
  end

  # POST /encoding_profiles
  # POST /encoding_profiles.json
  def create
    @encoding_profile = EncodingProfile.new(encoding_profile_params)

    respond_to do |format|
      if @encoding_profile.save
        format.html { redirect_to @encoding_profile, notice: 'Encoding profile was successfully created.' }
        format.json { render :show, status: :created, location: @encoding_profile }
      else
        format.html { render :new }
        format.json { render json: @encoding_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /encoding_profiles/1
  # PATCH/PUT /encoding_profiles/1.json
  def update
    respond_to do |format|
      if @encoding_profile.update(encoding_profile_params)
        format.html { redirect_to @encoding_profile, notice: 'Encoding profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @encoding_profile }
      else
        format.html { render :edit }
        format.json { render json: @encoding_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /encoding_profiles/1
  # DELETE /encoding_profiles/1.json
  def destroy
    @encoding_profile.destroy
    respond_to do |format|
      format.html { redirect_to encoding_profiles_url, notice: 'Encoding profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_encoding_profile
      @encoding_profile = EncodingProfile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def encoding_profile_params
      params.require(:encoding_profile).permit(:preset_id, :name, :description)
    end
end

app/controllers/media_items_controller.rb
class MediaItemsController < ApplicationController
  before_action :set_media_item, only: [:show, :edit, :update, :destroy]

  # GET /media_items
  # GET /media_items.json
  def index
    @media_items = MediaItem.all
  end

  # GET /media_items/1
  # GET /media_items/1.json
  def show
  end

  # GET /media_items/new
  def new
    @media_item = MediaItem.new
  end

  # GET /media_items/1/edit
  def edit
  end

  # POST /media_items
  # POST /media_items.json
  def create
    @media_item = MediaItem.new(media_item_params)

    respond_to do |format|
      if @media_item.save
        format.html { redirect_to @media_item, notice: 'Media item was successfully created.' }
        format.json { render :show, status: :created, location: @media_item }
      else
        format.html { render :new }
        format.json { render json: @media_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /media_items/1
  # PATCH/PUT /media_items/1.json
  def update
    respond_to do |format|
      if @media_item.update(media_item_params)
        format.html { redirect_to @media_item, notice: 'Media item was successfully updated.' }
        format.json { render :show, status: :ok, location: @media_item }
      else
        format.html { render :edit }
        format.json { render json: @media_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /media_items/1
  # DELETE /media_items/1.json
  def destroy
    @media_item.destroy
    respond_to do |format|
      format.html { redirect_to media_items_url, notice: 'Media item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_media_item
      @media_item = MediaItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def media_item_params
      params.require(:media_item).permit(:media_item_id, :s3_input_key, :s3_output_key, :cloudfront_url)
    end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :set_notification, only: [:show, :edit, :update, :destroy]

  # GET /notifications
  # GET /notifications.json
  def index
    @notifications = Notification.all
  end

  # GET /notifications/1
  # GET /notifications/1.json
  def show
  end

  # GET /notifications/new
  def new
    @notification = Notification.new
  end

  # GET /notifications/1/edit
  def edit
  end

  # POST /notifications
  # POST /notifications.json
  def create
    @notification = Notification.new(notification_params)

    respond_to do |format|
      if @notification.save
        format.html { redirect_to @notification, notice: 'Notification was successfully created.' }
        format.json { render :show, status: :created, location: @notification }
      else
        format.html { render :new }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notifications/1
  # PATCH/PUT /notifications/1.json
  def update
    respond_to do |format|
      if @notification.update(notification_params)
        format.html { redirect_to @notification, notice: 'Notification was successfully updated.' }
        format.json { render :show, status: :ok, location: @notification }
      else
        format.html { render :edit }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    @notification.destroy
    respond_to do |format|
      format.html { redirect_to notifications_url, notice: 'Notification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      @notification = Notification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notification_params
      params.require(:notification).permit(:topic, :subject, :message)
    end
end

app/controllers/sns_controller.rb
class SnsController < ApplicationController
  protect_from_forgery with: :null_session

  def sns_endpoint
    amz_message_type = request.headers['x-amz-sns-message-type']
    amz_sns_topic = request.headers['x-amz-sns-topic-arn']
    if amz_sns_topic == ::SnsTopicArn
      sns = ::SnsConnectionPool.get_sns_connection
      case amz_message_type
         when "SubscriptionConfirmation"
           Rails.logger.info "Received #{amz_message_type} notification."
           sns.confirm(request.raw_post, ::SnsTopicArn, ::SnsAuthOnUnsubscribe)
         when "Notification"
           sns.save_sns_notification(request.raw_post)
           Rails.logger.info "Received #{amz_message_type} notification."
         else
           Rails.logger.warning "Unknown notification type #{amz_message_type}."
      end
      render nothing: true
      ::SnsConnectionPool.release_sns_connection(sns)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/encoding_profiles_helper.rb
module EncodingProfilesHelper
end

app/helpers/media_items_helper.rb
module MediaItemsHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/encoding_profiles/_form.html.erb
<%= form_for(@encoding_profile) do |f| %>
  <% if @encoding_profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@encoding_profile.errors.count, "error") %> prohibited this encoding_profile from being saved:</h2>

      <ul>
      <% @encoding_profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :preset_id %><br>
    <%= f.text_field :preset_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/encoding_profiles/edit.html.erb
<h1>Editing Encoding Profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @encoding_profile %> |
<%= link_to 'Back', encoding_profiles_path %>

app/views/encoding_profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Encoding Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Preset</th>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @encoding_profiles.each do |encoding_profile| %>
      <tr>
        <td><%= encoding_profile.preset_id %></td>
        <td><%= encoding_profile.name %></td>
        <td><%= encoding_profile.description %></td>
        <td><%= link_to 'Show', encoding_profile %></td>
        <td><%= link_to 'Edit', edit_encoding_profile_path(encoding_profile) %></td>
        <td><%= link_to 'Destroy', encoding_profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Encoding profile', new_encoding_profile_path %>

app/views/encoding_profiles/new.html.erb
<h1>New Encoding Profile</h1>

<%= render 'form' %>

<%= link_to 'Back', encoding_profiles_path %>

app/views/encoding_profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Preset:</strong>
  <%= @encoding_profile.preset_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @encoding_profile.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @encoding_profile.description %>
</p>

<%= link_to 'Edit', edit_encoding_profile_path(@encoding_profile) %> |
<%= link_to 'Back', encoding_profiles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Catalogbuilder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/media_items/_form.html.erb
<%= form_for(@media_item) do |f| %>
  <% if @media_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@media_item.errors.count, "error") %> prohibited this media_item from being saved:</h2>

      <ul>
      <% @media_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :media_item_id %><br>
    <%= f.text_field :media_item_id %>
  </div>
  <div class="field">
    <%= f.label :s3_input_key %><br>
    <%= f.text_field :s3_input_key %>
  </div>
  <div class="field">
    <%= f.label :s3_output_key %><br>
    <%= f.text_field :s3_output_key %>
  </div>
  <div class="field">
    <%= f.label :cloudfront_url %><br>
    <%= f.text_field :cloudfront_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/media_items/edit.html.erb
<h1>Editing Media Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @media_item %> |
<%= link_to 'Back', media_items_path %>

app/views/media_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Media Items</h1>

<table>
  <thead>
    <tr>
      <th>Media item</th>
      <th>S3 input key</th>
      <th>S3 output key</th>
      <th>Cloudfront url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @media_items.each do |media_item| %>
      <tr>
        <td><%= media_item.media_item_id %></td>
        <td><%= media_item.s3_input_key %></td>
        <td><%= media_item.s3_output_key %></td>
        <td><%= media_item.cloudfront_url %></td>
        <td><%= link_to 'Show', media_item %></td>
        <td><%= link_to 'Edit', edit_media_item_path(media_item) %></td>
        <td><%= link_to 'Destroy', media_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Media item', new_media_item_path %>

app/views/media_items/new.html.erb
<h1>New Media Item</h1>

<%= render 'form' %>

<%= link_to 'Back', media_items_path %>

app/views/media_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Media item:</strong>
  <%= @media_item.media_item_id %>
</p>

<p>
  <strong>S3 input key:</strong>
  <%= @media_item.s3_input_key %>
</p>

<p>
  <strong>S3 output key:</strong>
  <%= @media_item.s3_output_key %>
</p>

<p>
  <strong>Cloudfront url:</strong>
  <%= @media_item.cloudfront_url %>
</p>

<%= link_to 'Edit', edit_media_item_path(@media_item) %> |
<%= link_to 'Back', media_items_path %>

app/views/notifications/_form.html.erb
<%= form_for(@notification) do |f| %>
  <% if @notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
      <% @notification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :topic %><br>
    <%= f.text_field :topic %>
  </div>
  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_area :subject %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_field :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notifications/edit.html.erb
<h1>Editing Notification</h1>

<%= render 'form' %>

<%= link_to 'Show', @notification %> |
<%= link_to 'Back', notifications_path %>

app/views/notifications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Notifications</h1>

<table>
  <thead>
    <tr>
      <th>Topic</th>
      <th>Subject</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notifications.each do |notification| %>
      <tr>
        <td><%= notification.topic %></td>
        <td><%= notification.subject %></td>
        <td><%= notification.message %></td>
        <td><%= link_to 'Show', notification %></td>
        <td><%= link_to 'Edit', edit_notification_path(notification) %></td>
        <td><%= link_to 'Destroy', notification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notification', new_notification_path %>

app/views/notifications/new.html.erb
<h1>New Notification</h1>

<%= render 'form' %>

<%= link_to 'Back', notifications_path %>

app/views/notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Topic:</strong>
  <%= @notification.topic %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @notification.subject %>
</p>

<p>
  <strong>Message:</strong>
  <%= @notification.message %>
</p>

<%= link_to 'Edit', edit_notification_path(@notification) %> |
<%= link_to 'Back', notifications_path %>